### ISSUE TITLE
Branched and deployed to heroku run provides can't GET

### ISSUE THREAD

**Issue by PantherTheCat** [Airblader/hipchat-byo-inspirobot#1]
Cannot GET /inspirobot/
http://inspirem.herokuapp.com/
Cannot GET /
Cannot GET /inspirobot

I have tried all of these. 

I used the git connector, and forked the package to my name so it would connect, Deployed - Build successful - page returns Cannot GET no matter what I do.

**Comment by Airblader** [comment]
Because there is no GET endpoint. There's only a POST endpoint since that is what Hipchat BYO uses. Of course you can modify the code to do the same on GET if you want.
